version: '3.0'
services:
  eosio-contract-api-filler:
    container_name: eosio-contract-api-filler
    build: .
    command: yarn run start:filler
    restart: on-failure
    depends_on:
      - eosio-contract-api-postgres
      - eosio-contract-api-redis
    volumes:
      - ./config:/home/application/app/config
    networks:
      - eosio-contract-api
  eosio-contract-api-server:
    container_name: eosio-contract-api-server
    build: .
    command: yarn run start:server
    restart: on-failure
    ports:
      - "9000:9000"
    depends_on:
      - eosio-contract-api-postgres
      - eosio-contract-api-redis
    volumes:
      - ./config:/home/application/app/config
    networks:
      - eosio-contract-api
  eosio-contract-api-redis:
    container_name: eosio-contract-api-redis
    image: redis:5-alpine
    restart: on-failure
    volumes:
      - ./docker/redis/data:/data
    networks:
      - eosio-contract-api
  eosio-contract-api-postgres:
    container_name: eosio-contract-api-postgres
    image: postgres:12
    restart: on-failure
    environment:
      - 'POSTGRES_USER=eosio-contract-api'
      - 'POSTGRES_PASSWORD=changeme'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - eosio-contract-api
networks:
  eosio-contract-api:
    driver: bridge
